apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::310481547117:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-FD0TPE2WBTZ7
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::310481547117:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
       - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-29T04:41:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3410"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2afcfd60-3afa-45d6-b1d2-b2741637e758
